name: 🐛 Bug Report
description: Something is wrong with Remix.
labels:
  - "bug:unverified"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping to improve Remix!

        ## The best bug report is a failing test!

        The fastest way to get a bug fixed is to add a failing test and send a pull request. **It's usually easy to do with our bug report test template**.

        1. Click the "Fork" button
        2. Open up the file [`integration/bug-report-test.ts`](https://github.com/remix-run/remix/blob/dev/integration/bug-report-test.ts) on your machine
        3. Follow the instructions!

        ## I'd rather just report the bug

        That's fine too! Go ahead and fill out this form.

  - type: input
    attributes:
      label: What version of Remix are you using?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
