name: 🐛 Bug Report
description: Something is wrong with Remix.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing!

        Do you need some help?
        ======================
        The issue tracker is meant for feature requests and bug reports only. This isn't the best place for
        support or usage questions. Questions here don't have as much visibility as they do elsewhere. Before
        you ask a question, here are some resources to get help first:

        - Read the docs: https://remix.run/docs
        - Explore examples: https://github.com/remix-run/remix/tree/dev/examples
        - Look for/ask questions on Stack Overflow: https://stackoverflow.com/questions/ask?tags=remix
        - Ask in GitHub Discussions: https://github.com/remix-run/remix/discussions
        - Ask in chat: https://rmx.as/discord

        ### Test Case Starter:
        https://stackblitz.com/github/remix-run/remix/tree/dev/examples/basic?file=app/root.tsx
  - type: checkboxes
    id: packages
    attributes:
      label: Which Remix packages are impacted?
      options:
        - label: "`remix` (Remix core)"
        - label: "`create-remix`"
        - label: "`@remix-run/architect`"
        - label: "`@remix-run/cloudflare-workers`"
        - label: "`@remix-run/dev`"
        - label: "`@remix-run/express`"
        - label: "`@remix-run/netlify`"
        - label: "`@remix-run/node`"
        - label: "`@remix-run/react`"
        - label: "`@remix-run/serve`"
        - label: "`@remix-run/server-runtime`"
        - label: "`@remix-run/vercel`"
  - type: input
    attributes:
      label: What version of Remix are you using?
    validations:
      required: true
  - type: input
    attributes:
      label: What version of Node are you using? Minimum supported version is 14.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
