blank_issues_enabled: false
contact_links:
  - name: Get Help
    url: https://github.com/remix-run/remix/discussions/new?category=q-a
    about:
      If you can't get something to work the way you expect, open a question in
      the Remix discussions.
  - name: Feature Request
    url: https://github.com/remix-run/remix/discussions/new?category=ideas
    about:
      We appreciate you taking the time to improve Remix with your ideas, but we
      use the Discussions for this instead of the issues tab 🙂.
