name: 💡 Feature Request
description: I want something added to Remix.
body:
  - type: markdown
    attributes:
      value: |
        We appreciate you taking the time to improve Remix with your ideas, but the issues tab is for issues. We
        use the discussions tab for feature discussions 🙂.

        - [Browse/search for an existing
        discussion](https://github.com/remix-run/remix/discussions/categories/ideas)
        - [Start a new discussion
        here](https://github.com/remix-run/remix/discussions/new?category=ideas)
