name: Format

on:
  push:
    branches:
      - main
      - dev

jobs:
  format:
    if: github.repository == 'remix-run/remix'
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.FORMAT_PAT }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Update Example and Template names
        run: node scripts/patchup-example-names.mjs

      - name: Format
        run: npm run format --if-present

      - name: Commit
        run: |
          git config --local user.email "hello@remix.run"
          git config --local user.name "Remix Run Bot"

          git add .
          if [ -z "$(git status --porcelain)" ]; then
            echo "💿 no formatting changed"
            exit 0
          fi
          git commit -m "chore: format"
          git push
          echo "💿 pushed formatting changes https://github.com/$GITHUB_REPOSITORY/commit/$(git rev-parse HEAD)"
