name: 📝 Comment on Release

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  comment:
    name: Comment on Release
    if: github.repository == 'remix-run/remix'
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: 📥 Install deps
        # even though this is called "npm-install" it does use yarn to install
        # because we have a yarn.lock and caches efficiently.
        uses: bahmutov/npm-install@v1

      - name: 📝 Comment on issues
        run: node ./scripts/release/comment.mjs
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ github.token }}
          VERSION: ${{ inputs.ref }}
