name: 🧪 Test (release)

on:
  push:
    branches:
      - release-*
    tags:
      - "v0.0.0-nightly-*"
    paths-ignore:
      - "docs/**"
      - "scripts/**"
      - "**/README.md"

jobs:
  test:
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/reusable-test.yml
    with:
      node_version: "[14, 16, 18]"
