name: 👟 Release Private
on:
  release:
    types: [published]

jobs:
  build:
    if: github.repository == 'remix-run/remix'
    runs-on: ubuntu-latest

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: 📥 Install deps
        run: yarn --frozen-lockfile

      - name: 🏗 Build
        run: yarn build

      - name: 🔐 Setup npm auth
        run: |
          echo "@remix-run:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGES_PUBLISH_TOKEN }}" >> ~/.npmrc

      - name: 🚀 Publish
        run: npm run publish:private
