name: 🧪 Test

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "docs/**"
      - "scripts/**"
      - "**/README.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**/*.md"

jobs:
  test:
    if: github.repository == 'remix-run/remix'
    uses: remix-run/remix/.github/workflows/reusable-test.yml@main
    with:
      node_version: '["latest"]'
