name: website

on:
  push:
    branches: [main]
    paths: [docs/**]
  release:
    types: [published]

jobs:
  website:
    if: github.repository == 'remix-run/remix'
    runs-on: ubuntu-latest

    steps:
      - name: Refresh the docs
        uses: fjogeleit/http-request-action@v1.8.1
        with:
          url: "${{ secrets.DOCS_REFRESH_URL }}?ref=${{ github.ref }}"
          method: "POST"
          customHeaders: '{"Authorization": "${{ secrets.DOCS_REFRESH_TOKEN }}"}'
